# Generated by Django 3.0.8 on 2020-07-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('About', models.CharField(max_length=500)),
                ('Insta', models.CharField(max_length=200)),
                ('Whatsapp', models.CharField(max_length=200)),
                ('Linkedin', models.CharField(max_length=200)),
            ],
        ),
    ]
