# Generated by Django 3.0.8 on 2020-07-31 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='About',
        ),
    ]
