# Generated by Django 3.0.8 on 2020-07-31 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_info_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='About',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
