# Generated by Django 3.0.8 on 2020-07-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_info_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Brief', models.TextField(max_length=200)),
                ('Desc', models.TextField(max_length=2000)),
            ],
        ),
    ]
