# Generated by Django 3.0.8 on 2020-07-31 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_articles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
